export enum CommonWeatherUnit {
  Metric = 'Metric',
  Standard = 'Standard',
  Imperial = 'Imperial',
}

export enum CommonWeatherLanguage {
  Afrikaans = 'af',
  Albanian = 'al',
  Arabic = 'ar',
  Azerbaijani = 'az',
  Bulgarian = 'bg',
  Catalan = 'ca',
  Czech = 'cz',
  Danish = 'da',
  German = 'de',
  Greek = 'el',
  English = 'en',
  Basque = 'eu',
  PersianFarsi = 'fa',
  Finnish = 'fi',
  French = 'fr',
  Galician = 'gl',
  Hebrew = 'he',
  Hindi = 'hi',
  Croatian = 'hr',
  Hungarian = 'hu',
  Indonesian = 'id',
  Italian = 'it',
  Japanese = 'ja',
  Korean = 'kr',
  Latvian = 'la',
  Lithuanian = 'lt',
  Macedonian = 'mk',
  Norwegian = 'no',
  Dutch = 'nl',
  Polish = 'pl',
  Portuguese = 'pt',
  PortuguesBrasil = 'pt_br',
  Romanian = 'ro',
  Russian = 'ru',
  Swedish = 'sv',
  Slovak = 'sk',
  Slovenian = 'sl',
  Spanish = 'sp',
  Serbian = 'sr',
  Thai = 'th',
  Turkish = 'tr',
  Ukrainian = 'ua',
  Vietnamese = 'vi',
  Chinese = 'zh_cn',
  ChineseTraditional = 'zh_tw',
  Zulu = 'zu',
}

export enum FiveDayWeatherForecastPartOfDay {
  Night = 'n',
  Day = 'd',
}
